//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Paper_Petrov_Fydyaev.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_MaterialList
    {
        public string NameMaterial { get; set; }
        public string TypeMaterial { get; set; }
        public double MinimumCount { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public string SuppliarName { get; set; }
        public decimal MaterialCost { get; set; }
        public int MaterialTypeID { get; set; }
        public int CountInPackage { get; set; }
        public string Description { get; set; }
        public int Unit { get; set; }
        public string Image { get; set; }
        public int MaterialID { get; set; }
    }
}
